# Generated by Django 2.1.2 on 2018-10-29 13:01

from django.db import migrations
from django.contrib.auth import get_user_model


User = get_user_model()


def set_active(apps, schema_editor):
    users = User.objects.filter(is_active=False).all()
    for u in users:
        u.is_active = True
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_active),
    ]
