# Generated by Django 2.1.2 on 2018-10-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('provider', 'provider_object_id'), ('provider', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('provider', 'provider_object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='organizer',
            unique_together={('provider', 'provider_object_id')},
        ),
    ]
