# Generated by Django 2.1.2 on 2018-10-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181013_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_ticket_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='Maximum ticket price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_ticket_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='Minimum ticket price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_currency',
            field=models.CharField(max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
