# Generated by Django 2.1.2 on 2018-10-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20181014_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_time',), 'verbose_name': 'event', 'verbose_name_plural': 'event'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ('name',), 'verbose_name': 'organizer', 'verbose_name_plural': ('organizer',)},
        ),
    ]
